<?php
/**
* Magedelight
* Copyright (C) 2015 Magedelight <info@magedelight.com>
*
* NOTICE OF LICENSE
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
*
* @category MD
* @package MD_Membership
* @copyright Copyright (c) 2015 Mage Delight (http://www.magedelight.com/)
* @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
* @author Magedelight <info@magedelight.com>
*/
?>
<?php if($this->getCollection()->getSize()): ?>
    <div class="toolbar">
        <div class="pager">
            <p class="amount">
                <?php if($this->getLastPageNum()>1): ?>
                    <?php echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                    <?php else: ?>            
                    <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>                    
                    <?php endif; ?>
            </p>
            <div class="limiter">
                <label><?php echo $this->__('Show') ?></label>
                <select onchange="setLocation(this.value)">
                    <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                        <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                            <?php echo $_limit ?>
                        </option>
                        <?php endforeach; ?>
                </select> <?php echo $this->__('per page') ?>
            </div>

            <?php echo $this->getPagerHtml() ?>

        </div>
        <?php if( $this->isExpanded() ): ?>
            <div class="sorter">
                <?php if( $this->isEnabledViewSwitcher() ): ?>
                    <p class="view-mode">
                        <?php $_modes = $this->getModes(); ?>
                        <?php if($_modes && count($_modes)>1): ?>
                            <label><?php echo $this->__('View as') ?></label>
                            <?php foreach ($this->getModes() as $_code=>$_label): ?>
                                <?php if($this->isModeActive($_code)): ?>
                                    <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>
                                    <?php else: ?>
                                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                    </p>
                    <?php endif; ?>

                <div class="sort-by">
                    <label><?php echo $this->__('Sort By') ?></label>
                    <select onchange="setLocation(this.value)" title="<?php echo $this->__('Sort By') ?>">
                        <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                            <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                                <?php echo $this->__($_order) ?>
                            </option>
                            <?php endforeach; ?>
                    </select>
                    <?php if($this->getCurrentDirection() == 'desc'): ?>
                        <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/sort_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
                        <?php else: ?>
                        <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/sort_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
                        <?php endif; ?>
                </div>
            </div>
            <?php endif; ?>

    </div>
    <?php endif ?>
